version: '3' # Версия docker-compose

services:
  redis:
      image: redis:latest # Docker-образ для Redis

  web:
    image: nginx:latest # Docker-образ для веб-сервера (здесь используется Nginx)
    ports:
      - "8001:80" # Проброс портов: 80 на хосте к 80 в контейнере
    volumes:
      - ./web:/usr/share/nginx/html # Монтируем локальную папку в контейнер

  db:
    image: postgres # Docker-образ для PostgreSQL

    env_file:
      - .env

    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata # Монтируем volume для сохранения данных

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    tty: true
    command:
      - ./run.sh
      - 0.0.0.0:8000
    ports:
      - "8000:8000" # Проброс портов: 8000 на хосте к 8000 в контейнере

    env_file:
      - .env

    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO

    env_file:
      - .env

    depends_on:
      - redis
      - app # Зависимость от сервиса приложения

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django

    env_file:
      - .env

    depends_on:
      - redis
      - app # Зависимость от сервиса приложения


volumes:
  postgres-data: # Название volume для PostgreSQL
