# Generated by Django 4.2.4 on 2023-08-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='data',
            new_name='date_payment',
        ),
    ]
